[project]

name        = "robcogen2"
version     = "0.1.0"
description = "Code generator for articulated robot dynamics"
authors     = [
    { name = "Marco Frigerio", email = "mfgit.6uvfu@passinbox.com" }
]

license = "BSD-3-Clause"
readme = "readme.md"

requires-python = ">=3.9"

dependencies = [
    "kgprim >= 0.1.3",
    "robot-model-tools >= 0.3.0",
    "ctgen >= 0.3.0",
    "lupa >= 2.1",
]

[project.urls]
Homepage   = "https://github.com/mfrigerio17/robcogen2"
Repository = "https://github.com/mfrigerio17/robcogen2"

[project.scripts]
rcg = "robcogen.cmdline:main"


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.lua", "*/*.lua", "static/*"]
