%% Test of the Octave function generated by RobCoGen to compute the Joint Space
%% Inertia Matrix (JSIM), for floating base robots.
%%
%% Usage: [ROY, ME] = test_jsim_fb(ROY_MODEL, ROBCOGEN_MODEL)
%%
%% ROY_MODEL is the robot model (a data structure) in Roy's format.
%%
%% ROBCOGEN_MODEL is the struct obtained from `init.m` in the RobCoGen-erated
%% Octave code.
%%
%% See readme.md for more information and general documentation about the tests.
%%
%% Author: Marco Frigerio
%
%%% This file is part of the Octave test functions for RobCoGen.

function [roy, me] = test_jsim_fb(roy_model, rcg_model)

dof = length(roy_model.jtype);
q   = rand(dof,1) * 2;
qd  = rand(dof,1) * 2;

% RobCoGen implementation:
rcg_model.updateK(q(7:end));
rcg_model.jsim.update_composite_inertia();
rcg_model.jsim.update_JSIM();

me.M  = rcg_model.jsim.H;
me.F  = rcg_model.jsim.F;
me.Ic = rcg_model.jsim.base_Ic();


% Roy's routine
[roy.H, roy.C] = HandC( roy_model, q, qd );

% Compute the Jacobian that maps the velocity of the virtual floating base joints
%  to the spatial velocity of the robot base
[_,_, J] = bodyToFBJointMotion(q(1:6), zeros(6,1), zeros(6,1));
Jinv = inv(J); % Jacobian inverse

% The Jacobian is required to convert the inertia matrix computed with Roy's
% algorithm, which works on a model of the robot where the floating base is
% emulated with 6 more joints connecting the fixed world with the base.
% The conversion is required because the acceleration (or velocity, or anything
% else) at the 6 joints it is NOT the same, in general, as the spatial velocity
% of the robot base.

roy.Ic = Jinv' * roy.H(1:6,1:6) * Jinv;  % the composite inertia of the robot base
roy.M  = roy.H(7:end, 7:end);            % the actuated-joint-space inertia matrix
roy.F  = Jinv' * roy.H(1:6, 7:end);      % the F block, upper right block of the JSIM


err.Ic = roy.Ic - me.Ic;
err.M  = roy.M  - me.M;
err.F  = roy.F  - me.F;

err.Ic( abs(err.Ic) < 1E-5 ) = 0;
err.M ( abs(err.M)  < 1E-5 ) = 0;
err.F ( abs(err.F)  < 1E-5 ) = 0;

disp(err.Ic);
disp('');
disp(err.M);
disp('');
disp(err.F);

