%% Test of the C++ inverse dynamics generated by RobCoGen, for fixed base
%% robots.
%%
%% Usage: [ROY, ME] = testcpp_id(ROY_MODEL, EXE)
%%
%% ROY_MODEL is the robot model (a data structure) in Roy's format.
%%
%% EXE is the full path of the program running the C++ RobCoGen inverse
%% dynamics for the same robot. The program must take the following command
%% line argument
%%   - status, velocity and acceleration vectors in joint space
%%   - (optional) the full path with a text file with external forces
%%
%% That is, the program must be executable with something like the following:
%%    "EXE <q'> <qd'> <qdd'> [<path to fext>]"
%%
%% See readme.md for more information and general documentation on the inputs
%% of this function.
%%
%% Author: Marco Frigerio
%
%%% This file is part of the Octave test functions for RobCoGen.

function [roy, me] = testcpp_id(roy_model, exe)

dof = length(roy_model.jtype);

q   = rand(dof,1);
qd  = rand(dof,1);
qdd = rand(dof,1);

% q   = zeros(dof,1);
% qd  = zeros(dof,1);
% qdd = zeros(dof,1);

%
% Random external forces
%
for i=1 : roy_model.NB
  fext{i} = rand(6, 1);
  %fext{i} = zeros(6, 1);
end

%
% Writes a file with the external forces
%
%%% ! WARNING ! %%% Check the readme for a note about external forces

fid = fopen('fext.txt', 'w');

for i=1 : roy_model.NB
  fprintf(fid, "%f %f %f %f %f %f\n", fext{i});
end
fclose(fid);
fextFile = [pwd '/fext.txt']; % full absolute path of the external forces file

%
% Run the C++ implementation
%
[foo me] = system( [ exe ' ' num2str([q', qd', qdd']) ' ' fextFile] );
me = str2num(me);

%
% Run Featherstone's routine. It wants the fext in global coordinates (sigh..)
% See the readme
%
roy = ID(roy_model, q, qd, qdd, fext);
err = roy - me;

%amp = uint8(abs((err * 100) ./ feath)); % percentage of the error

err( abs(err) < 1E-5 ) = 0;

display([ roy, me, err ]);

