%% Test of the C++ algorithm for the Joint Space Inertia Matrix (JSIM) generated
%% by RobCoGen, for floating base robots.
%%
%% Usage: [ROY, ME, ERROR] = testcpp_jsim_fb(ROY_MODEL, EXE)
%%
%% ROY_MODEL is the robot model (a data structure) in Roy's format.
%%
%% EXE is the full path of the program running the C++ code generated by
%% RobCoGen for the computation of the JSIM, for the same robot.
%% The program must take command line arguments for each coordinate of the
%% joint status vector.
%%
%% That is, the program must be executable in this form:
%%    "EXE q0 q1 .. qn"
%%
%% See readme.md for more information and general documentation on the inputs
%% of this function.
%%
%% Author: Marco Frigerio
%
%%% This file is part of the Octave test functions for RobCoGen.

function [roy, me, err] = testcpp_jsim_fb(roy_model, exe)

dof = length(roy_model.jtype);

q   = rand(dof,1) * 2;
qd  = rand(dof,1) * 2;

% Robogen implementation:
[foo output] = system( [ exe ' ' num2str([q(7:end)'])] );
output = str2num(output);

me.Ic = output(1:6,1:6);
me.F  = output(1:6,7:end);
me.M  = output(7:end,7:end);

% Featherstone's routine
[H,C] = HandC( roy_model, q, qd );

% Compute the Jacobian that maps the velocity of the virtual floating base joints
%  to the spatial velocity of the robot base
[foo_qd foo_qdd J] = bodyToFBJointMotion(q(1:6), zeros(6,1), zeros(6,1));
Jinv = inv(J); % Jacobian inverse

% The Jacobian is required to convert the inertia matrix computed with Roy's
% algorithm, which works on a model of the robot where the floating base is
% emulated with 6 more joints connecting the fixed world with the actual robot.
% The conversion is required because the acceleration (or velocity, or anything
% else) at the 6 joints it is NOT the same, in general, as the spatial velocity
% of the robot base.
% Note that this point is totally similar as the conversion joints-space/
% operational-space, for a 6-dof manipulator

roy.Ic = Jinv' * H(1:6,1:6) * Jinv;  % the composite inertia of the robot base
roy.M  = H(7:end, 7:end);            % the actuated-joint-space inertia matrix
roy.F  = Jinv' * H(1:6, 7:end);      % the F block, upper right block of the JSIM

err.Ic = roy.Ic - me.Ic;
err.F  = roy.F  - me.F;
err.M  = roy.M  - me.M;

err.Ic( abs(err.Ic)<1E-5 ) = 0;
err.F ( abs(err.F )<1E-5 ) = 0;
err.M ( abs(err.M )<1E-5 ) = 0;

% only display the errors, otherwise it's too messy
disp(err.Ic);
disp('');
disp(err.F);
disp('');
disp(err.M);

