
%% Test of the Octave inverse dynamics generated by RobCoGen, for fixed base
%% robots.
%%
%% Usage: [ROY, ME] = test_id(ROY_MODEL, ROBCOGEN_MODEL)
%%
%% ROY_MODEL is the robot model (a data structure) in Roy's format.
%%
%% ROBCOGEN_MODEL is a structure with two fields, 'xm' and 'ip', respectively
%% the coordinate transforms for motion vectors and the inertia properties of
%% the links of the robot.
%%
%% See readme.md for more information and general documentation about the test
%% functions.
%%
%% Author: Marco Frigerio
%
%%% This file is part of the Octave test functions for RobCoGen.
%%% Copyright © 2025, Marco Frigerio
%%% See the LICENSE file for more information.

function [roy, me] = test_id(roy_model, robcogen_model, robcogen_ID)

dof = length(roy_model.jtype);

q   = rand(dof,1);
qd  = rand(dof,1);
qdd = rand(dof,1);

% Random external forces
for i = 1:dof
  fext{i} = rand(6,1);
end

% RobCoGen implementation:
robcogen_model.xm.updateAll(q);
me.tau = robcogen_model.ID(qd, qdd, fext);

% Roy's implementation
roy.tau = ID(roy_model, q, qd, qdd, fext);

% Display the results and the differences
err = roy.tau - me.tau;
err( abs(err) < 1E-5 ) = 0;

display([roy.tau, me.tau, err]);


