%% Test of the Octave forward dynamics generated by RobCoGen, for fixed base
%% robots.
%%
%% Usage: [ROY, ME] = test_fd(ROY_MODEL, ROBCOGEN_MODEL)
%%
%% ROY_MODEL is the robot model (a data structure) in Roy's format.
%%
%% ROBCOGEN_MODEL is the struct obtained from `init.m` in the RobCoGen-erated
%% Octave code.
%%
%% See readme.md for more information and general documentation about the tests.
%%
%% Author: Marco Frigerio
%
%%% This file is part of the Octave test functions for RobCoGen.

function [roy, me] = test_fd(roy_model, robcogen_model)

dof = length(roy_model.jtype);

q   = rand(dof,1);
qd  = rand(dof,1);
tau = rand(dof,1);

% Random external forces
for i = 1:dof
  fext{i} = rand(6,1);
end

% RobCoGen implementation:
robcogen_model.updateK(q);
me.qdd = robcogen_model.FD(qd, tau, fext);

% Roy's implementation
roy.qdd = FDab(roy_model, q, qd, tau, fext);

% Display the results and the differences
err = roy.qdd - me.qdd;
err( abs(err) < 1E-5 ) = 0;

display([roy.qdd, me.qdd, err]);


