%% Test of the Octave function generated by RobCoGen to compute the Joint Space
%% Inertia Matrix (JSIM), for fixed base robots.
%%
%% Usage: [ROY, ME] = test_jsim(ROY_MODEL, ROBCOGEN_MODEL)
%%
%% ROY_MODEL is the robot model (a data structure) in Roy's format.
%%
%% ROBCOGEN_MODEL is the struct obtained from `init.m` in the RobCoGen-erated
%% Octave code.
%%
%% See readme.md for more information and general documentation about the tests.
%%
%% Author: Marco Frigerio
%
%%% This file is part of the Octave test functions for RobCoGen.

function [roy, me] = test_jsim(roy_model, robcogen_model)


dof = length(roy_model.jtype);
q   = rand(dof,1) * 2;
qd  = rand(dof,1) * 2;

% RobCoGen implementation:
robcogen_model.updateK(q);
robcogen_model.jsim.update_composite_inertia();
robcogen_model.jsim.update_JSIM();
me.H = robcogen_model.jsim.H;

% Roy's implementation
[roy.H, roy.C] = HandC( roy_model, q, qd ); % Featherstone's routine

err = roy.H - me.H;
err( abs(err) < 1E-3 ) = 0;

disp(err);
