local template = [[
%% A structure with the «robot.name» robot model in the format described
%% in "A beginner's guide to 6-D vectors (part 2)" by Roy Featherstone.
%%
%% «thisfunc.ret_val» = «thisfunc.name(robot)»(«thisfunc.args.geometry_constants», «thisfunc.args.geometry_parameters», «thisfunc.args.inertia_constants», «thisfunc.args.inertia_parameters»)
%%
%% «thisfunc.ret_val» is the data struct with the robot model data conforming to
%% Roy's model.
%%
%% «thisfunc.args.geometry_constants» is a struct with all the geometric
%% constant properties of the robot model.
%% «thisfunc.args.inertia_constants» is the same for inertial constant properties.
%%
%% «thisfunc.args.geometry_parameters» and «thisfunc.args.inertia_parameters»
%% are structs with values for the parametric model properties. Not required if
%% the original robot model is not parametric. The first struct is for geometry
%% parameters, the second for inertial ones.
%%
%% This file has been automatically generated by RobCoGen.

function «thisfunc.ret_val» = «thisfunc.name(robot)»(«thisfunc.args.geometry_constants», «thisfunc.args.geometry_parameters», «thisfunc.args.inertia_constants», «thisfunc.args.inertia_parameters»)

«thisfunc.ret_val».robotname = '«robot.name»';

@if robot.isFloatingBase then
«thisfunc.ret_val».NB = «robot.tree.nB» + 5;
«thisfunc.ret_val».parent = zeros(1, «robot.tree.nB» + 5);

«thisfunc.ret_val».jtype(1:6) = {'Px', 'Py', 'Pz', 'Rx', 'Ry', 'Rz'};
«thisfunc.ret_val».parent(1:6) = [0 1 2 3 4 5];

for i = 1:6
    % For the 'I' field, a loop until i=5 would be enough
    «thisfunc.ret_val».I{i} = mcI( 0, [0,0,0], zeros(3) );
    % 'Xtree' instead must be initialized up to i=6
    «thisfunc.ret_val».Xtree{i} = eye(6);
end

@    for name,link in sorted_links(robot) do
@       local id = commons.linkArrayIndex(link)
«thisfunc.ret_val».parent(«id+5») = «commons.linkArrayIndex(robot.treeutils.parent(link))+5»;
@    end

@    for _,joint in pairs(robot.tree.joints) do
«thisfunc.ret_val».jtype{«commons.jointStateVectorIndex(joint)»+6} = «jointType(joint)»;
@    end

@    for _,joint in pairs(robot.tree.joints) do
«thisfunc.ret_val».Xtree{«commons.jointStateVectorIndex(joint)»+6} = «xtree(joint)»;
@    end

@    for name,link in sorted_links(robot, "include_base_if_floating") do
@       local id = commons.linkArrayIndex(link)
@             ip = inertial_data.byLink(link)
I = «ns_qualifier»RigidBodyInertia.makeTensor3D(«valueof(ip.moments.ixx)»,«valueof(ip.moments.iyy)»,«valueof(ip.moments.izz)»,«valueof(ip.moments.ixy)»,«valueof(ip.moments.ixz)»,«valueof(ip.moments.iyz)»);
«thisfunc.ret_val».I{«id+5»} = «ns_qualifier»RigidBodyInertia.makeTensor6D(«valueof(ip.mass)», [«valueof(ip.com.x)»; «valueof(ip.com.y)»; «valueof(ip.com.z)»], I);

@    end
@else
«thisfunc.ret_val».NB = «robot.tree.nB-1»;
«thisfunc.ret_val».parent = zeros(1, «robot.tree.nB-1»);

@    for name,link in sorted_links(robot) do
@       local id = commons.linkArrayIndex(link)
«thisfunc.ret_val».parent(«id») = «commons.linkArrayIndex(robot.treeutils.parent(link))»;
@    end

@    for _,joint in pairs(robot.tree.joints) do
«thisfunc.ret_val».jtype{«commons.jointStateVectorIndex(joint)»} = «jointType(joint)»;
@    end

@    for _,joint in pairs(robot.tree.joints) do
«thisfunc.ret_val».Xtree{«commons.jointStateVectorIndex(joint)»} = «xtree(joint)»;
@    end

@    for name,link in sorted_links(robot) do
@       local id = commons.linkArrayIndex(link)
@       local ip = inertial_data.byLink(link)
I = «ns_qualifier»RigidBodyInertia.makeTensor3D(«valueof(ip.moments.ixx)»,«valueof(ip.moments.iyy)»,«valueof(ip.moments.izz)»,«valueof(ip.moments.ixy)»,«valueof(ip.moments.ixz)»,«valueof(ip.moments.iyz)»);
«thisfunc.ret_val».I{«id»} = «ns_qualifier»RigidBodyInertia.makeTensor6D(«valueof(ip.mass)», [«valueof(ip.com.x)»; «valueof(ip.com.y)»; «valueof(ip.com.z)»], I);
@    end
@end
]]

return template
