local cmakefile = [[
@local name = robot.name
@local nameLow = name:lower()
#-------------------------------------------------------------------------------
#
# CMake file for the generated C++ code for the robot «name»
#
# Author: Marco Frigerio
# Note: this file has been generated by RobCoGen.
#       Do not edit unless you know what you are doing.
#-------------------------------------------------------------------------------

# Project configuration
cmake_minimum_required(VERSION 3.12...3.22)
project(«name»_robcogen)

@if not templateAll then
set(LIB_NAME "«libname»")
@end

add_compile_definitions(EIGEN_NO_DEBUG)
add_compile_options(-std=c++11 -Wall -O3)
include_directories(.) # so that local includes with < > will also work


set(HEADERS
    ./«headers.main»
    ./«headers.types»
    ./«headers.transforms»
    ./«headers.inertia»
    ./«headers.constants»
    ./«headers.inv_dyn»
@if templateAll then
    ./«impl_files.constants»
    ./«impl_files.transforms»
    ./«impl_files.inertia»
    ./«impl_files.inv_dyn»
)
@else
)

set(SOURCES
    ./«impl_files.constants»
    ./«impl_files.transforms»
    ./«impl_files.inertia»
    ./«impl_files.inv_dyn»
)

# Add library
add_library(${LIB_NAME} SHARED ${SOURCES})

# Install the shared library
install(TARGETS ${LIB_NAME} LIBRARY DESTINATION lib)
@end

# Install (ie copy) header files
install(FILES ${HEADERS} DESTINATION include/«incpath»)


# The playground main()
add_executable(playground «impl_files.playground»)
target_link_libraries(playground ${LIB_NAME})


# Tests
add_executable(test-id    tests/«impl_files.test_cmdline_id»)
add_executable(test-cons  tests/«impl_files.test_consistency»)

target_link_libraries(test-id   ${LIB_NAME})
target_link_libraries(test-cons ${LIB_NAME})
]]

local function generator_cmake(robot, configurator, env)
    env.libname = configurator.txtCfg.make.libName(robot)
    env.incpath = configurator.txtCfg.make.incPath(robot)
    return function()
        return RCG.utils.templates.tpl_eval(cmakefile, env)
    end
end

return generator_cmake
