local cmakefile = [[
#-------------------------------------------------------------------------------
#
# CMake file for the generated C++ code for the robot «robot.name»
#
# Note: this file has been generated by RobCoGen.
#       Do not edit unless you know what you are doing.
#-------------------------------------------------------------------------------

# Project configuration
cmake_minimum_required(VERSION 3.12...3.22)
project(«robot.name»_robcogen)

@if not templateAll then
set(LIB_NAME "«libname»")
@end

add_compile_definitions(EIGEN_NO_DEBUG)
add_compile_options(-std=c++11 -Wall -O3)
include_directories(.) # so that local includes with < > will also work


set(HEADERS
    ./«headers.main»
    ./«headers.types»
    ./«headers.traits»
    ./«headers.transforms»
    ./«headers.inertia»
    ./«headers.constants»
    ./«headers.inv_dyn»
    ./«headers.jsim»
    ./«headers.fwd_dyn»
    ./«headers.aba_hinv»
@if templateAll then
    ./«impl_files.constants»
    ./«impl_files.transforms»
    ./«impl_files.inertia»
    ./«impl_files.inv_dyn»
    ./«impl_files.jsim»
    ./«impl_files.fwd_dyn»
    ./«impl_files.aba_hinv»
)
@else
)

set(SOURCES
    ./«impl_files.constants»
    ./«impl_files.transforms»
    ./«impl_files.inertia»
    ./«impl_files.inv_dyn»
    ./«impl_files.jsim»
    ./«impl_files.fwd_dyn»
    ./«impl_files.aba_hinv»
)

# Add library
add_library(${LIB_NAME} SHARED ${SOURCES})

# Install the shared library
install(TARGETS ${LIB_NAME} LIBRARY DESTINATION lib)
@end

# Install (ie copy) header files
install(FILES ${HEADERS} DESTINATION include/«incpath»)


# The playground main()
add_executable(playground «impl_files.playground»)
target_link_libraries(playground ${LIB_NAME})


# Tests
add_executable(test-id    tests/«impl_files.test_cmdline_id»)
add_executable(test-jsim  tests/«impl_files.test_cmdline_jsim»)
add_executable(test-fd    tests/«impl_files.test_cmdline_fd»)
add_executable(test-cons  tests/«impl_files.test_consistency»)

target_link_libraries(test-id   ${LIB_NAME})
target_link_libraries(test-jsim ${LIB_NAME})
target_link_libraries(test-fd   ${LIB_NAME})
target_link_libraries(test-cons ${LIB_NAME})
]]

local cmake_to_test_installation = [[
#-------------------------------------------------------------------------------
#
# CMake file for the generated C++ code for the robot «robot.name»
#
# This file is meant to build test executables against the __installed__
# headers and library built from the generated code.
#
# Use it only after 'make install' from the main build folder, to test if
# everything was installed properly.
#
# If you installed in a non-default prefix, you must of course instruct cmake
# accordingly.
#
# Note: this file has been generated by RobCoGen.
#       Do not edit unless you know what you are doing.
#-------------------------------------------------------------------------------
cmake_minimum_required(VERSION 3.12...3.22)
project(«robot.name»_robcogen_test_install)

add_executable(test-cons  «impl_files.test_consistency»)
target_link_libraries(test-cons "«libname»")

]]

local function generator_cmake(robot, configurator, env)
    env.libname = configurator.txtCfg.make.libName(robot)
    env.incpath = configurator.txtCfg.make.incPath(robot)
    return {
        main = function()
            return RCG.utils.templates.tpl_eval(cmakefile, env)
        end,
        test_for_installed_files = function()
            return RCG.utils.templates.tpl_eval(cmake_to_test_installation, env)
        end,
    }
end

return generator_cmake
