local header_template = [[
#ifndef «include_guard»
#define «include_guard»

#include "«headers.types»"

${ns.open}

«tpl»struct «class» {
@ for _, constant in ipairs(constants) do
    $<constant_declaration>
@ end
};

${ns.close}

@if templateAll then
#include "«impl_files.constants»"
@end

#endif
]]

local impl_template = [[
@ -- when using constexpr, the source file is unnecessary, we leave it empty
@if meta.constants.avoid_constexpr then
@   if not templateAll then
#include "«headers.constants»"

using «ns.qualifier»::«types.scalar»;
@   end

@   for _, constant in ipairs(constants) do
$<constant_definition>
@   end
@end
]]

local function generators_constants(robot, configurator, given_env)
    local genutils  = RCG.utils.templates

    -- shallow copy the evaluation environment, and adds required entries
    local env = {}
    for k,v in pairs(given_env) do
        env[k] = v
    end
    env.class = env.meta.constants.class
    env.classqualifier = env.meta.constants.class
    env.tpl = ''
    if env.templateAll then
        local scalarTpl = env.common.scalarTpl( env.meta.constants.class )
        env.classqualifier = scalarTpl.class.in_qualifier
        env.tpl = scalarTpl.heading .. '\n'
    end

    -- Massage the inertia constants and put them in a table for the template.
    -- We want to generate a C++ constant for each named-constant in the model,
    -- but also for each expression of a constant which may be the value of a
    -- field.
    local fieldName = configurator.txtCfg.ids.inertia_prop
    env.constants = {}
    for _, c in genutils.poly_ipairs(robot.inertia.constants) do

        -- The constant itself must result in an entry
        table.insert(env.constants, {name=c.name, value=c.value})

        -- Then, we check the expressions (e.g. 2*C) and we add a separate
        -- entry for each occurrence of such expression. Note that expressions
        -- include the identity, that is, the constant itself.
        -- This way we support generation of meaningful aliases, as in
        --    double mymass{1};
        --    double link1_mass{mymass};
        --    ...
        local list = robot.inertia.expressionsOfConstant(c)
        for _, expr in genutils.poly_ipairs(list.expressions) do
            local str_value = configurator.symbolicExpressionToCode(expr.expr, {[expr.arg.symbol]=c.name})
            for _, fieldMeta in genutils.poly_ipairs(list.backtrackingData(expr)) do
                local fname = fieldName(fieldMeta.link, fieldMeta.ipfield)
                -- We must skip the entry if the field name we generated happens
                -- to be the same as the name of the constant itself. Otherwise
                -- we would generate twice the same C++ variable (imagine the
                -- user had picked 'link1_mass' instead of 'mymass').
                if fname ~= c.name then
                    table.insert(env.constants, {name=fname, value=str_value})
                end
                -- Note:
                -- Such a name clash can also happen for each of the "reified"
                -- constants (robot attributes which are float literals in the
                -- model, but the importing of the robot-model-tools transforms
                -- in named constants). Those appear only once by construction,
                -- so they only occur in one identity expression, thus we have
                -- a name clash if the naming policy of the robot-model-tools
                -- is the same as the policy here in 'fieldName'
            end
        end
    end
    -- For the geometric constants, we only insert the constants themselves.
    -- The transforms generator (CtGen) does its own things with the derived
    -- constants
    for _, c in genutils.poly_ipairs(robot.kinematics.constants) do
        table.insert(env.constants, {name=c.name, value=c.value})
    end

    -- The sub-templates for the declaration/definition of a constant
    local declaration = 'static constexpr «types.scalar» «constant.name»{«constant.value»};'
    local definition  = ''
    if env.meta.constants.avoid_constexpr then
        declaration = 'static const «types.scalar» «constant.name»;'
        definition  = '«tpl»const «types.scalar» «ns.qualifier»::«classqualifier»::«constant.name»{«constant.value»};'
    end


    local function gen_header()
        env.include_guard = env.includeGuard(configurator.files.h_constants)
        return genutils.tpl_eval(header_template, env, {}, {constant_declaration=declaration})
    end

    local function gen_implementation()
        return genutils.tpl_eval(impl_template, env, {}, {constant_definition=definition})
    end

    -- The next ones are generators of the C++ expression that would resolve to
    -- the value of the given constant.
    -- They are provided to configure other code generators, so that they will
    -- generate correct code, consistent with the code generated by this
    -- template.

    -- At the moment, such expressions are very simply just class-qualified
    -- identifiers, because we generate the constants as static members of a
    -- container class.

    local function gen_read_access_inertia_constant(link, ipfield)
        return env.classqualifier ..'::'.. configurator.txtCfg.ids.inertia_prop(link, ipfield)
    end

    local function gen_read_access_geom_constant(constant)
        return env.classqualifier ..'::'.. constant.name
    end

    return {
        header = gen_header,
        source = gen_implementation,
        readAccessExprForInertiaConstant = gen_read_access_inertia_constant,
        readAccessExprForGeometricConstant = gen_read_access_geom_constant,
    }
end

return generators_constants
